#!/bin/bash

#
# The entrance script into the wander build system. This controls the entire
# process, and makes sure everything works properly
#
# @author the_DJDJ
# @since  8.3-systemd
#

# Clear the screen
clear

# Set up the installer
source install/setup
source install/welcome
source install/sudo

# Do some initialisation
source build/init/prerequisites
source build/init/filesystem
source build/init/preparations

# Take down the installer
source install/takedown
