#!/bin/bash

#
# The entrance script into the wander build system. This controls the entire
# process, and makes sure everything works properly
#
# @author the_DJDJ
# @since  8.3-systemd
#

# Set up the installer
source install/setup

# Clear the screen
clear

# Display a welcome message
source install/welcome

# Firstly, check that we are running as a superuser
source install/sudo

# Check that our host system meets the requirements
source build/prerequisites
if [ $success -ne 0 ]; then
	# What do we do if the system does not meet the minimum requirements?
	read -p  " Do you want to continue the build anyway? (y/n) " reply
	case $reply in
		[Yy])	echo "" ;;
		[Nn])	echo "Exiting. See you soon!"
				source install/takedown
				exit ;;
		   *)	echo "Unrecognised input. Exiting."
				source install/takedown
				exit ;;
	esac
else
	# Do some nice spacing
	echo ""
	echo ""
fi

# Start with the filesystem preparations
source build/init/filesystem

# Take down the installer
source install/takedown
