#!/bin/bash

#
# This file contains the scripts for taking down the config used in the
# installer
#
# @author the_DJDJ
# @since  8.3-systemd
#

# Take down the config file location
unset CONFIG_FILE

# And remove the actual stored settings
unset swap_partition
unset os_partition
unset format_partition
unset wander
unset sources

unset build_temp_binutils_1
unset build_temp_gcc_1
unset build_temp_linux_headers
unset build_temp_glibc
unset build_temp_libstdcpp
unset build_temp_binutils_2
unset build_temp_gcc_2
