#!/bin/bash

#
# This file contains the scripts for setting up the installer
#
# @author the_DJDJ
# @since  8.3-systemd
#

# Set up global variables
source install/var/setup

# Set up the colours
source install/colour/setup

# Load the config
source install/config/setup

# Create the log directories
rm -rf logs					&> /dev/null
mkdir logs					&> /dev/null
mkdir logs/init				&> /dev/null
mkdir logs/temp				&> /dev/null

# Change the permissions
chown -v wander logs		&> /dev/null
chown -v wander logs/init	&> /dev/null
chown -v wander logs/temp	&> /dev/null
