#!/bin/bash

#
# This file contains the scripts for creating a nice, user-friendly welcome
# message.
#
# @author the_DJDJ
# @since  8.3-systemd
#

# Show a nice welcome message
echo -e "${COLOUR_SET_BOLD}Welcome to the Wander build system!"
echo -e ""
echo -e "${COLOUR_RESET}This script will allow for Wander ($WANDER_VERSION) to be built."
echo -e ""

# Load the config
source install/config
